// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/codemode/authz"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInvocationResolver creates a new instance of MockInvocationResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvocationResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvocationResolver {
	mock := &MockInvocationResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInvocationResolver is an autogenerated mock type for the InvocationResolver type
type MockInvocationResolver struct {
	mock.Mock
}

type MockInvocationResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInvocationResolver) EXPECT() *MockInvocationResolver_Expecter {
	return &MockInvocationResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockInvocationResolver
func (_mock *MockInvocationResolver) Resolve(ctx context.Context) (authz.Subject, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 authz.Subject
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (authz.Subject, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) authz.Subject); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(authz.Subject)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInvocationResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockInvocationResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInvocationResolver_Expecter) Resolve(ctx any) *MockInvocationResolver_Resolve_Call {
	return &MockInvocationResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx)}
}

func (_c *MockInvocationResolver_Resolve_Call) Run(run func(ctx context.Context)) *MockInvocationResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInvocationResolver_Resolve_Call) Return(subject authz.Subject, err error) *MockInvocationResolver_Resolve_Call {
	_c.Call.Return(subject, err)
	return _c
}

func (_c *MockInvocationResolver_Resolve_Call) RunAndReturn(run func(ctx context.Context) (authz.Subject, error)) *MockInvocationResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
