// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/codemode"
	"github.com/meigma/codemode/authz"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Describe provides a mock function for the type MockService
func (_mock *MockService) Describe(name codemode.CapabilityName) (codemode.Description, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Describe")
	}

	var r0 codemode.Description
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(codemode.CapabilityName) (codemode.Description, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(codemode.CapabilityName) codemode.Description); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(codemode.Description)
	}
	if returnFunc, ok := ret.Get(1).(func(codemode.CapabilityName) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Describe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Describe'
type MockService_Describe_Call struct {
	*mock.Call
}

// Describe is a helper method to define mock.On call
//   - name codemode.CapabilityName
func (_e *MockService_Expecter) Describe(name any) *MockService_Describe_Call {
	return &MockService_Describe_Call{Call: _e.mock.On("Describe", name)}
}

func (_c *MockService_Describe_Call) Run(run func(name codemode.CapabilityName)) *MockService_Describe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 codemode.CapabilityName
		if args[0] != nil {
			arg0 = args[0].(codemode.CapabilityName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Describe_Call) Return(v codemode.Description, err error) *MockService_Describe_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockService_Describe_Call) RunAndReturn(run func(name codemode.CapabilityName) (codemode.Description, error)) *MockService_Describe_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type MockService
func (_mock *MockService) Execute(ctx context.Context, subject authz.Subject, program codemode.Program) (any, error) {
	ret := _mock.Called(ctx, subject, program)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, authz.Subject, codemode.Program) (any, error)); ok {
		return returnFunc(ctx, subject, program)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, authz.Subject, codemode.Program) any); ok {
		r0 = returnFunc(ctx, subject, program)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, authz.Subject, codemode.Program) error); ok {
		r1 = returnFunc(ctx, subject, program)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockService_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - subject authz.Subject
//   - program codemode.Program
func (_e *MockService_Expecter) Execute(ctx any, subject any, program any) *MockService_Execute_Call {
	return &MockService_Execute_Call{Call: _e.mock.On("Execute", ctx, subject, program)}
}

func (_c *MockService_Execute_Call) Run(run func(ctx context.Context, subject authz.Subject, program codemode.Program)) *MockService_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 authz.Subject
		if args[1] != nil {
			arg1 = args[1].(authz.Subject)
		}
		var arg2 codemode.Program
		if args[2] != nil {
			arg2 = args[2].(codemode.Program)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Execute_Call) Return(v any, err error) *MockService_Execute_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockService_Execute_Call) RunAndReturn(run func(ctx context.Context, subject authz.Subject, program codemode.Program) (any, error)) *MockService_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockService
func (_mock *MockService) Search(query string) (codemode.SearchResponse, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 codemode.SearchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (codemode.SearchResponse, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) codemode.SearchResponse); ok {
		r0 = returnFunc(query)
	} else {
		r0 = ret.Get(0).(codemode.SearchResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - query string
func (_e *MockService_Expecter) Search(query any) *MockService_Search_Call {
	return &MockService_Search_Call{Call: _e.mock.On("Search", query)}
}

func (_c *MockService_Search_Call) Run(run func(query string)) *MockService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Search_Call) Return(v codemode.SearchResponse, err error) *MockService_Search_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockService_Search_Call) RunAndReturn(run func(query string) (codemode.SearchResponse, error)) *MockService_Search_Call {
	_c.Call.Return(run)
	return _c
}
