// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/codemode/authz"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthorizer creates a new instance of MockAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorizer {
	mock := &MockAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthorizer is an autogenerated mock type for the Authorizer type
type MockAuthorizer struct {
	mock.Mock
}

type MockAuthorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizer) EXPECT() *MockAuthorizer_Expecter {
	return &MockAuthorizer_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function for the type MockAuthorizer
func (_mock *MockAuthorizer) Authorize(context1 context.Context, authorizationInput authz.AuthorizationInput) error {
	ret := _mock.Called(context1, authorizationInput)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, authz.AuthorizationInput) error); ok {
		r0 = returnFunc(context1, authorizationInput)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthorizer_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockAuthorizer_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - context1 context.Context
//   - authorizationInput authz.AuthorizationInput
func (_e *MockAuthorizer_Expecter) Authorize(context1 any, authorizationInput any) *MockAuthorizer_Authorize_Call {
	return &MockAuthorizer_Authorize_Call{Call: _e.mock.On("Authorize", context1, authorizationInput)}
}

func (_c *MockAuthorizer_Authorize_Call) Run(run func(context1 context.Context, authorizationInput authz.AuthorizationInput)) *MockAuthorizer_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 authz.AuthorizationInput
		if args[1] != nil {
			arg1 = args[1].(authz.AuthorizationInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthorizer_Authorize_Call) Return(err error) *MockAuthorizer_Authorize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthorizer_Authorize_Call) RunAndReturn(run func(context1 context.Context, authorizationInput authz.AuthorizationInput) error) *MockAuthorizer_Authorize_Call {
	_c.Call.Return(run)
	return _c
}
